# Travis CI
language: python

python:
  - "3.6"

cache:
  - pip

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - python setup.py .

script:
 - pytest jupter_plotly_dash --cov=jupyter_plotly_dash --cov-report term-missing
