#!/usr/bin/env bash
#
virtualenv -p python3.6 env
source env/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install -r dev_requirements.txt
#python setup.py develop
pip install .
